celery added
Aalis/instagram_stats pull request #4
Opened 2024-01-09 18:16 UTC by Aalis

2024-01-11 08:46 UTC, vladysllav requested changes

2024-01-11 08:46 UTC, vladysllav commented on instagram_stats/settings.py
> +CELERY_BROKER_URL = "redis://localhost:6379/0"
Це краще винести у .env

2024-01-11 08:46 UTC, vladysllav commented on inst_profiles/views.py
> +    example_task()
celery таски не так викликаються, ти просто викликав функцію, а потрібно викликати так щоб воно відкладено на фоні працювало через delay або apply_async

2024-01-11 23:13 UTC, Aalis commented on instagram_stats/settings.py
> +CELERY_BROKER_URL = "redis://localhost:6379/0"
Вніс зміни по твоїм зауваженням. До цієї вітки, але не знаю як правильно робити щоб ти побачив

2024-01-12 09:45 UTC, vladysllav approved these changes

2024-01-12 09:55 UTC, merged